---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(gcookbook)
library(gridExtra)
library(ggrepel)
source("./util.R")
```

```{r}
heightweight

```

```{r}
ggplot(heightweight, aes(x=ageYear, y = heightIn, shape=sex, color=sex)) + geom_point() + scale_shape_manual(values = c(1,2)) + scale_color_brewer(palette="Set1")
```

```{r}
ggplot(heightweight, aes(x=ageYear, y=heightIn, color = sex, size = weightLb)) + geom_point(alpha=0.5) + scale_size_area()

```

```{r}
ggplot(diamonds, aes(x=carat, y=price)) +  geom_point()
ggplot(diamonds, aes(x=carat, y=price, alpha = 0.1)) + geom_point()
ggplot(diamonds, aes(x=carat, y=price)) + stat_bin2d()
ggplot(diamonds, aes(x=carat, y=price)) + stat_bin2d(bins = 50)  + scale_fill_gradient(low = "lightblue", high = "red", limits = c(0, 6000))
```


```{r}
ggplot(heightweight, aes(x=ageYear, y=heightIn)) + stat_smooth(method = lm, level = 0.99, color = "red") + geom_point()
```

```{r}
predictvals(lm(heightIn ~ ageYear, heightweight), "ageYear", "heightIn")
```

```{r}
models <- heightweight %>% group_by(sex) %>% do(model = lm(heightIn ~ ageYear, .)) %>% ungroup()
predvals <- models %>% group_by(sex) %>% do(predictvals(.$model[[1]], xvar="ageYear", yvar = "heightIn"))

ggplot(heightweight, aes(x=ageYear, y= heightIn, color = sex)) + geom_point() + geom_line(data =predvals) + facet_grid(. ~ sex)
```


```{r}
countries_sub <- countries %>% filter(Year == 2009 & healthexp > 2000)
ggplot(countries_sub, aes(x=healthexp, y=infmortality)) + geom_point() + geom_text(aes(label = Name), size = 4)
ggplot(countries_sub, aes(x=healthexp, y=infmortality)) + geom_point() + geom_label_repel(aes(label = Name), size = 3)
```

