---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(gcookbook)
library(gridExtra)
library(ggrepel)
library(grid)
source("./util.R")

#library(hexbin)
#library(MASS)
#library(viridis)
#library(viridisLite)
library(maps)
library(mapproj)
library(rgdal)
library(raster)
library(rgdal)
library(sf)

```

```{r}
jp0 <- getData(name="GADM", country="Japan", level=0)
jp1 <- getData(name="GADM", country="Japan", level=1)
```
```{r}
plot(jp1)
```

```{r}
#summary(jp1)
jp1_sp <- spTransform(jp1, CRS("+proj=longlat +datum=WGS84"))
summary(jp1_sp)
```

```{r}
ggplot() +
     geom_polygon(data = jp1_sp, aes(x=long, y = lat, group = group), color = "black", fill = "white")
```



```{r}
jp_shp <- st_read("./map/gadm36_JPN_shp/gadm36_JPN_1.shp") # https://gadm.org/download_country_v3.html downlaod Shapefile
head(jp_shp, 10)
summary(jp_shp)
```

```{r}
ggplot(jp_shp) + geom_sf(aes(fill = ENGTYPE_1)) + theme_void() + theme(legend.position = c(0.75, 0.4))
```

```{r}
pop <- read.csv("data/pop.csv")
pop$pref = factor(pop$pref)
jp_pop_shp <- merge(jp_shp, pop, by.x="NL_NAME_1",by.y="pref")
jp_pop_shp %>% head()
write.csv(jp_pop_shp, "data/jp_pop_shp.csv")
```

```{r}
ggplot(data = jp_pop_shp, aes(fill = population)) + 
  geom_sf() + 
  theme_void() + 
  theme(legend.position = c(0.75, 0.4)) + 
  scale_fill_gradient2(low = "blue", mid = "grey90", high = "red", midpoint = 7000)
```

```{r}
ggplot(pop, aes(x=population)) + geom_density()
```

